[package]
name = "simulated-annealing-TSP"
version = "0.1.0"
authors = ["RodrigoVelazquez99 <rodrigo_velazquez99@ciencias.unam.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
